= llm-d Deployment Guide

:icons: font

[NOTE.icon-cogs] 
.Your Starting Point

This page provides a series of interactive (Arcade) walkthroughs to help you provision and configure your OpenShift environment with components to deploy the llm-d QuickStart using the Red Hat Demo Platform (RHDP). Follow these four steps in order, and you'll be ready to deploy.

'''

=== 1. Lab Setup: Overview and Steps

This Arcade experience covers requesting or ordering the Lab Environment item from The Red Hat Demp Platform (RHDP) catalog. 

Below is the link to the Red Hat Demo Platform (RHDP) Catalog item, the steps to order the catalog 


https://catalog.demo.redhat.com/catalog?item=babylon-catalog-prod/sandboxes-gpte.ocp-wksp.prod&utm_source=webapp&utm_medium=share-link[Red Hat OpenShift Container Platform Cluster (AWS), window=blank]
 
'''
++++

<iframe src="https://demo.arcade.software/t8r64IXbTp9k7H4zdlRq?embed&embed_mobile=inline&embed_desktop=inline&show_copy_link=true" width="100%" height="600px" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="clipboard-write" muted> </iframe> 

++++

=== 2. Openshift Container Platform llm-d Checklist

This Arcade reviews the OCP Console steps or checklist to ensure an  LLM-D compatible environment. It with logging into the OpenShift Container Platform Console and validating:

 * The OCP Version - needs to be 4.19+, which includes new Intelligent Inference Scheduler (API Gateway).
 * Validate the the GPU machineSet needs to be created, and ensure Worker nodes are ready.
 * Validate which Operators are installed in the cluster. 

'''
++++


<iframe src="https://demo.arcade.software/scyKqZfQIPidN6XsPezv?embed&embed_mobile=inline&embed_desktop=inline&show_copy_link=true" width="100%" height="600px" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="clipboard-write" muted> </iframe> 

++++

=== 3. Getting Started in the OpenShift Cluster
This experience starts with a running RHDP environment and shows the steps to log into the environment and validate the MachineSets and worker nodes available to the cluster.

'''

++++

<iframe src="https://demo.arcade.software/iDl0tHu8c55tzoTZoWe3?embed&embed_mobile=inline&embed_desktop=inline&show_copy_link=true" width="100%" height="600px" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="clipboard-write" muted> </iframe> 

++++


=== 4. Configuring the Cluster (Operators)

This experience uses the AI BU Services GitHub repository to clone setup files. It shows how to:

 * Deploy the prerequisite installer for OpenShift 4.19
 * Manually install two Operators that where missing.

'''

++++

<iframe src="https://demo.arcade.software/PmJgJNoo3ZE09ryfH7Vv?embed&embed_mobile=inline&embed_desktop=inline&show_copy_link=true" width="100%" height="600px" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="clipboard-write" muted> </iframe> 


++++



=== 5. Deploying the Demo

We deploy the intelligent inference demo but run into resources constraints.  Wakl through the OpenShift Console to determine where failures might exist.

'''

++++

<iframe src="https://demo.arcade.software/Lo1Aoc2e04KKMvif55fw?embed&embed_mobile=inline&embed_desktop=inline&show_copy_link=true" width="100%" height="600px" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="clipboard-write" muted> </iframe> 


++++

=== 6. Validating that it's Working 

Let's run a query to insure our Inference Server is listening. 

'''

++++

<iframe src="https://demo.arcade.software/aaYK3RnOKT3QIvR7b2Qf?embed&embed_mobile=inline&embed_desktop=inline&show_copy_link=true" width="100%" height="600px" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="clipboard-write" muted> </iframe> 


++++
